server {
    listen 80;

    # Serve the frontend dashboard
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # ── Book Service ─────────────────────────────────────────────────────────
    location /api/books/health {
        proxy_pass         http://book-service:8001/health;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    location /api/books {
        proxy_pass         http://book-service:8001/books;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Correlation-ID $http_x_correlation_id;
    }

    # ── Inventory Service ────────────────────────────────────────────────────
    location /api/inventory/health {
        proxy_pass         http://inventory-service:8002/health;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    location /api/inventory {
        proxy_pass         http://inventory-service:8002/inventory;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    # ── Notification Service ─────────────────────────────────────────────────
    location /api/notifications/health {
        proxy_pass         http://notification-service:8003/health;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    location /api/notifications {
        proxy_pass         http://notification-service:8003/notifications;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }
}
